### ISSUE TITLE
[BUG] Linked List append

### ISSUE THREAD

**Issue by matheusfrancisco** [xico-labs/data_structures_and_algorithms_py#2]
We have a problem at singly_linked_list.py at append method:

When we design the append we think of using it with append at the beginning and append at the end

Problem:
When we append at end of list it seems that they are duplicating the element at the beginning of the list.

```python
In [2]: from pydsx import SinglyLinkedList
In [3]: l = SinglyLinkedList()
In [4]: l.append(1)
In [8]: l.append(2,tail=True)
In [11]: print(len(l))
for i in l:
    ...:     print(i)
    ...: 
    ...: 
>>2
>>1
>>2

```

And when the first entry in the list is with tail=True we have this error
![image](https://user-images.githubusercontent.com/6428732/85555286-25df5200-b5fc-11ea-9421-14811d057d02.png)

## Where to look
`pydsx.singly_linked_list.linked_list.py`

```python

    def append(self, value, first=True, tail=False):
        if value is None:
            return None
        if first and not tail:
            self._append_first(value)
        if tail:
            self._append_tail(value)
```
Remember try to write test:
`tests.test_linked_list.py`

**Comment by Aditya1001001** [comment]
Can I work on this issue?

**Comment by matheusfrancisco** [comment]
You can open a pull request.

To run the tests: 
`make test
`
in the root folder

 Thank you very much for fixing this bug.
